apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-arc
  namespace: argo
spec:
  destination:
    namespace: arc-systems
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    chart: actions-runner-controller
    targetRevision: {{ (index .Values "gh-arc" "targetRevision") }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true